### PR TITLE
Fix NativeEventEmitter warnings

### LINKED ISSUE #221: `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
Title and
```
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

### PR DESCRIPTION
**Pull request by bcye**
This PR adds empty methods to fix the warnings issued because it does not expose listener methods. It should fix #221 (more infos in [this pr](https://github.com/dotintent/react-native-ble-plx/pull/901))

### CODE REVIEW

**Review by jjcavallo5 — APPROVED** [review]
Fixes NativeEventEmitter warnings

**Comment by asfernandes** [comment]
Is this going to be merged?
Is this project active?

File: android/src/main/java/net/no_mad/tts/TextToSpeechModule.java [hunk 1]
```diff
@@ -525,4 +525,14 @@ private void sendEvent(String eventName, WritableMap params) {
...
                 .emit(eventName, params);
     }
+    
+    @ReactMethod
+    public void removeListeners(Integer count) {
+        // Keep: Required for RN built in Event Emitter Calls.
+    }
+
+    @ReactMethod
+    public void addListener(Integer count) {
```
Comment (fatidian1) [inline android/src/main/java/net/no_mad/tts/TextToSpeechModule.java:535]: It should be:
`public void addListener(String eventName) {`
Otherwise application throws an error.

**Review by fatidian1 — COMMENTED** [review]
Needs a small fix, causes application to crash.

File: android/src/main/java/net/no_mad/tts/TextToSpeechModule.java (hunk 1 above)
Comment (walterholohan) [reply android/src/main/java/net/no_mad/tts/TextToSpeechModule.java:535]: @fatidian1 you raise a PR then I will merge for you
